download :; git clone git@github.com:esmail-abdulfattah/fbesag
build :;  make -C fbesag/src -f ../../../Makefile.generic CC="$(CC)" CXX="$(CXX)" FC="$(FC)" FLAGS="$(FLAGS)" INC="$(INC)"
clean :; rm -rf fbesag
.PHONY: download build clean

