download :; git clone git@github.com:XiangYEstats/INLAcircular.git
build :;  make -C INLAcircular/src-cloglike -f ../../../Makefile.generic -B CC="$(CC)" CXX="$(CXX)" FC="$(FC)" FLAGS="$(FLAGS)" INC="$(INC)"
clean :; rm -rf INLAcircular
.PHONY: download build clean
