download :; git clone --single-branch --branch inla git@github.com:eliaskrainski/INLAtools
build :;  make -C INLAtools/src -f ../../../Makefile.generic CC="$(CC)" CXX="$(CXX)" FC="$(FC)" FLAGS="$(FLAGS)" INC="$(INC)"
clean :; rm -rf INLAtools
.PHONY: download build clean
