download :; git clone --single-branch --branch inla git@github.com:eliaskrainski/INLAspacetime.git
build :;  make -C INLAspacetime/src -f ../../../Makefile.generic CC="$(CC)" CXX="$(CXX)" FC="$(FC)" FLAGS="$(FLAGS)" INC="$(INC)"
clean :; rm -rf INLAspacetime
.PHONY: download build clean
