#!/usr/bin/env bash

logit() {
    echo "$myself: $*"
}

fixpermissions () {
    for d in "$@"; do
	echo "Working with [$d]"
	find $d -print | while read f; do
	    if [ -d "$f" -o -x "$f" ]; then
		chmod 755 "$f"
	    elif [ -f "$f" ]; then
		chmod 644 "$f"
	    elif [ -L "$f" ]; then
		echo dont change links ["$f"]
	    else
		echo unknown type ["$f"]
	    fi
	done
    done
}

myself=${0##*/}

BINPREFIX=$(echo $1)
logit "Location of binaries is $BINPREFIX"

TDIR=$(echo $2)
logit "Temporary directory is$TDIR"
test -d $TDIR || mkdir -p $TDIR

logit "Check the build directory and make sure its empty"

TMPDIR=$(echo $TDIR/.BuildINLA)
test -d $TMPDIR && rm -rf $TMPDIR
mkdir -p $TMPDIR

LOGFILE=$TMPDIR/LOG

logit "Logfile for the installation is $LOGFILE"

logit "Define version number and find the hgid"
epoch=$(date +%s)
VERSION=0.0-$epoch
logit "    VERSION=$VERSION"
bdate=$(date -d @$epoch +%Y%m%d%H%M)
date=$(date -d @$epoch)
hg=$(hg parents --template 'hgid: {node|short}  date: {date|date}')

logit "rsync r-inla.org to get the doc-files"
rsync -auv --delete r-inla.org $TMPDIR >> $LOGFILE 2>&1 || exit 1

logit "rsync rinla/. to the build directory"
mkdir -p $TMPDIR/INLA
rsync -auv --exclude '/*~' --exclude '/inst/bin' --exclude TAGS  rinla/. $TMPDIR/INLA >> $LOGFILE 2>&1 || exit 1

tt=$TMPDIR/.tt

logit "populate the bin-directory"
rsync -auv --exclude '/*~' $BINPREFIX/. $TMPDIR/INLA/inst/bin >> $LOGFILE 2>&1 || exit 1

logit "Generate BinaryFiles"
( cd $TMPDIR/INLA && find inst/bin/ ) > $tt && \
	     mv -f $tt $TMPDIR/INLA/BinaryFiles

logit "Modify the inla.version-function"
cat $TMPDIR/INLA/R/version.R | \
    awk '/^[ \t]*rinla[.]hgid *=/{ print "    rinla.hgid = ", "inla.trim(\"" hg      "\")"; next;}
         /^[ \t]*inla[.]hgid *=/{  print "    inla.hgid  = ", "inla.trim(\"" hg "\")"; next;}
         /^[ \t]*date *=/{       print "    date       = ", "inla.trim(\"" date    "\")"; next;}
         /^[ \t]*bdate *=/{      print "    bdate      = ", "inla.trim(\"" bdate   "\")"; next;}
         /^[ \t]*version *=/{      print "    version      = ", "inla.trim(\"" version   "\")"; next;}
	 {print}' hg="$hg" hg="$hg" bdate="$bdate" date="$date" version="$VERSION" > $tt && \
	     mv -f $tt $TMPDIR/INLA/R/version.R

logit "Modify the DESCRIPTION file"
## Modify the DESCRIPTION file
desc="$TMPDIR/INLA/DESCRIPTION"
{
    egrep -v '^(Version:|Date:)' $desc
    echo "Version: $VERSION"
    echo "Date: $(date '+%Y-%m-%d') ($hg)"
} > $tt && mv -f $tt $desc


logit "Generate the NAMESPACE file"
## generate the exports defined in the R-files
{
    echo ""
    echo "# The functions to be exported are defined in the R-code with"
    echo "# lines as:"
    echo "# ## Export: func1"
    echo "# ## Export: func1 func2"
    echo "# etc..."

    find $TMPDIR/INLA/R -name \*.R | while read f; do
	egrep "^## *Export *:" $f | while read ff; do
	    echo "$ff" | awk -F: '{print $2}' | awk '{for(i=1;i<=NF;i++) print $i}' | \
		awk '{nf = split($0, a, /!/)
                      if (nf == 2) print "S3method(" a[1] ", "  a[2] ")"
                      if (nf == 1) print "export(" a[1] ")" }'
	done
    done
} >> $TMPDIR/INLA/NAMESPACE || exit 1

logit "Fix file-permissions"
fixpermissions $TMPDIR/INLA >> $LOGFILE 2>&1

logit "Compile the INLA manual"
(cd $TMPDIR/ && R --vanilla CMD Rd2pdf --no-preview --batch INLA ) >> $LOGFILE 2>&1 || exit 1
md="$TMPDIR/INLA/inst/doc/manual"
test -d $md || mkdir $md
cp $TMPDIR/INLA.pdf $md

logit "Build the INLA package"
(cd $TMPDIR/ && R --vanilla CMD build --resave-data INLA ) >> $LOGFILE 2>&1 || exit 1

INLA=$(echo $TMPDIR/INLA_$VERSION.tar.gz)
tgzINLA=${INLA%%.tar.gz}.tgz
mv $INLA $tgzINLA 
mv $tgzINLA .

logit "Package built!"

package=$(echo INLA_$VERSION.tgz)
logit "You can install it using 'R --vanilla CMD INSTALL $package'"
