#!/usr/bin/env bash
## Prove the freshly built inla binary computes, not just links: install the
## R package from this checkout, point it at the binary, and run a small
## model with a known answer. Fails on any R error, a non-finite marginal
## likelihood, or parameter estimates away from the truth.
##
## Knobs: PREFIX (default: <repo>/local) -- must match ci/build.sh.
set -e -o pipefail

ROOT=$(cd "$(dirname "$0")/.." && pwd)
PREFIX=${PREFIX:-$ROOT/local}
INLA_BIN=$PREFIX/bin/inla

## 1. The binary answers at all. (libR.so lives outside the default loader
##    path; harmless when the binary was built without libR. The directory
##    differs per family, so ask R itself.)
R_HOME_DIR=$(R RHOME 2>/dev/null || echo /usr/lib/R)
export LD_LIBRARY_PATH="$R_HOME_DIR/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
"$INLA_BIN" -ping

## 2. Package dependencies into a private, user-writable library
##    (cached by the workflow so the install runs once). On Ubuntu, prefer
##    Posit's mirror: it serves prebuilt Linux binaries of CRAN packages,
##    so nothing needs compiling; plain CRAN is the fallback.
echo "== R dependencies =="
export R_LIBS_USER=$PREFIX/Rlib
mkdir -p "$R_LIBS_USER"
## Guarded: /etc/os-release does not exist on macOS, and sourcing a missing
## file is fatal under set -e.
if [ -r /etc/os-release ]; then . /etc/os-release; fi
if [ "${ID:-}" = "ubuntu" ] && [ -n "${VERSION_CODENAME:-}" ]; then
    export SMOKE_CRAN_REPOS="https://packagemanager.posit.co/cran/__linux__/${VERSION_CODENAME}/latest https://cloud.r-project.org"
else
    export SMOKE_CRAN_REPOS="https://cloud.r-project.org"
fi
Rscript --vanilla -e '
    lib   <- Sys.getenv("R_LIBS_USER")
    repos <- strsplit(Sys.getenv("SMOKE_CRAN_REPOS"), " ")[[1]]
    need  <- c("fmesher", "lifecycle", "rlang", "withr", "MatrixModels",
               "INLAspacetime")
    miss  <- setdiff(need, rownames(installed.packages()))
    if (length(miss))
        install.packages(miss, lib = lib, repos = repos)
'

## 3. The package's NAMESPACE is generated, not tracked: create it the same
##    way upstream does (roxygen; see rinla/R/Makefile) when it is missing.
##    The testthat_print definition mirrors that Makefile's document() call.
echo "== R package NAMESPACE =="
if [ ! -f "$ROOT/rinla/NAMESPACE" ]; then
    ## Roxygen's loader performs a minimal install, which itself requires
    ## some NAMESPACE file -- seed a placeholder that roxygen immediately
    ## replaces with the generated one. (Upstream never hits this: a
    ## previously generated NAMESPACE is always present in their tree.)
    ## The signature line matters: roxygen only overwrites a NAMESPACE that
    ## declares itself roxygen-generated.
    echo '# Generated by roxygen2: do not edit by hand' > "$ROOT/rinla/NAMESPACE"
    if ! Rscript --vanilla -e '
        lib   <- Sys.getenv("R_LIBS_USER")
        repos <- strsplit(Sys.getenv("SMOKE_CRAN_REPOS"), " ")[[1]]
        if (!requireNamespace("roxygen2", quietly = TRUE))
            install.packages("roxygen2", lib = lib, repos = repos)
        assign("testthat_print", function(...) print(...), envir = globalenv())
        roxygen2::roxygenize(commandArgs(TRUE)[1])
    ' "$ROOT/rinla"; then
        rm -f "$ROOT/rinla/NAMESPACE"      # do not leave the placeholder behind
        exit 1
    fi
    grep -q "^export" "$ROOT/rinla/NAMESPACE" \
        || { echo "ERROR: NAMESPACE was not regenerated"; rm -f "$ROOT/rinla/NAMESPACE"; exit 1; }
fi

## 4. The R package from this checkout (R side only; it ships no binaries,
##    the binary comes from ci/build.sh via the inla.call option below).
echo "== installing the R package =="
R CMD INSTALL --library="$R_LIBS_USER" --no-docs --no-help --no-byte-compile \
    "$ROOT/rinla"

## 4b. The in-tree fbesag companion package. Its model function is compiled
##     INTO the binary (external-packages -> cgeneric-table.h); the R package
##     only assembles the data, so installing from the checkout tests exactly
##     the cgeneric code this build ships.
echo "== installing fbesag (in-tree) =="
R CMD INSTALL --library="$R_LIBS_USER" --no-docs --no-help --no-byte-compile \
    "$ROOT/external-packages/fbesag/fbesag"

echo "== running the model =="

## 5. A small Gaussian model with a known answer. When TESTMODEL_DIR is set,
##    the model's input files are also exported there (keep=TRUE), so other
##    jobs can run the bare binary on a real model without needing R.
Rscript --vanilla - "$INLA_BIN" "${TESTMODEL_DIR:-}" "${INLA_SMTP:-}" <<'EOF'
argv <- commandArgs(trailingOnly = TRUE)
library(INLA)
inla.setOption(inla.call = argv[1])
inla.setOption(num.threads = "2:1")

## INLA_SMTP names a second sparse-matrix backend to check. The models
## below then run TWICE -- once on the default backend, once on this one --
## and the two marginal likelihoods must agree. Linking against a solver
## proves nothing about whether it computes the same posterior.
smtp <- if (length(argv) >= 3 && nzchar(argv[3])) argv[3] else ""

set.seed(1)
n   <- 300
x   <- rnorm(n)
idx <- 1:n
y   <- 1 + 0.7 * x + rnorm(n, sd = 0.3) + rnorm(n, sd = 0.2)

r <- inla(y ~ x + f(idx, model = "iid"),
          data   = data.frame(y = y, x = x, idx = idx),
          family = "gaussian")

stopifnot(is.finite(r$mlik[1]))
b <- r$summary.fixed
stopifnot(abs(b["(Intercept)", "mean"] - 1.0) < 0.1)
stopifnot(abs(b["x", "mean"] - 0.7) < 0.1)
cat("smoke test OK: mlik =", r$mlik[1], "\n")

## The same model through the alternative backend. Both are exact
## factorizations of the same precision matrix, so the marginal likelihoods
## differ only by arithmetic ordering -- a mismatch beyond that means the
## backend is wrong, not merely different.
if (nzchar(smtp)) {
    cat("== backend:", smtp, "==\n")
    inla.setOption(smtp = smtp)
    rs <- inla(y ~ x + f(idx, model = "iid"),
               data   = data.frame(y = y, x = x, idx = idx),
               family = "gaussian")
    stopifnot(is.finite(rs$mlik[1]))
    ## The backends factorize the same matrices but sit under different BLAS
    ## libraries, and INLA re-optimizes per run -- tiny arithmetic
    ## differences move the optimizer's stopping point, which shows up as
    ## ~1e-2 in mlik. The bar here is "same posterior", not "same bits":
    ## the parameter estimates must recover the truth exactly as the
    ## default-backend run does, and mlik must agree to well under anything
    ## a real defect (wrong logdet, wrong solve) would produce.
    bs <- rs$summary.fixed
    stopifnot(abs(bs["(Intercept)", "mean"] - 1.0) < 0.1)
    stopifnot(abs(bs["x", "mean"] - 0.7) < 0.1)
    d <- abs(rs$mlik[1] - r$mlik[1])
    cat(sprintf("mlik default=%.6f  %s=%.6f  |diff|=%.2e\n",
                r$mlik[1], smtp, rs$mlik[1], d))
    if (d > 5e-2)
        stop(sprintf("%s disagrees with the default backend by %.3e", smtp, d))
    cat(smtp, "agrees with the default backend\n")
}

## An rgeneric model: the only part of the binary that calls back INTO R
## while it runs. It is worth its own check because nothing else here
## exercises that path, and in a build with INLA_WITH_LIBR_DLOPEN it also
## proves the runtime library loading -- the binary locates the libR of
## whatever R is driving it and evaluates the model's R functions through
## it. A plain "the model converged" result is not evidence of that.
cat("== rgeneric ==\n")
rg <- inla.rgeneric.define(inla.rgeneric.iid.model, n = 30)
set.seed(2)
yy  <- rnorm(30)
iid <- 1:30
rr  <- inla(yy ~ -1 + f(iid, model = rg),
            data = data.frame(yy = yy, iid = iid),
            family = "gaussian")
stopifnot(is.finite(rr$mlik[1]))
stopifnot(nrow(rr$summary.random$iid) == 30)
cat("rgeneric OK: mlik =", rr$mlik[1], "\n")

## Built-in cgeneric models. The model functions live in the BINARY
## (cgeneric-mapper: the shlib argument is ignored for registered names), so
## this is the only part of the suite that exercises the external-packages
## objects and the mapper. Under INLA_SMTP each model runs on both backends
## and the marginal likelihoods must agree -- the cgeneric path hands the
## backend a precision assembled per iteration, which nothing above covers.
check_both <- function(fit, label, tol = 5e-2) {
    old <- inla.getOption("smtp"); on.exit(inla.setOption(smtp = old), add = TRUE)
    r1 <- fit()
    stopifnot(is.finite(r1$mlik[1]))
    cat(sprintf("%s: mlik(default) = %.6f\n", label, r1$mlik[1]))
    if (nzchar(smtp)) {
        inla.setOption(smtp = smtp)
        r2 <- fit()
        stopifnot(is.finite(r2$mlik[1]))
        d <- abs(r2$mlik[1] - r1$mlik[1])
        cat(sprintf("%s: mlik(%s) = %.6f  |diff| = %.2e\n", label, smtp, r2$mlik[1], d))
        if (d > tol)
            stop(sprintf("%s: %s disagrees with the default backend by %.3e",
                         label, smtp, d))
    }
    invisible(r1)
}

## fbesag on a chain graph. The input is the intrinsic PRECISION (D - A):
## get_fbesag scales it via inla.scale.model, which aborts on an adjacency
## (indefinite matrix) -- the demo's all-ones matrix is equally degenerate.
cat("== cgeneric: fbesag ==\n")
library(fbesag)
nf  <- 20
Af  <- matrix(0, nf, nf)
for (i in 1:(nf - 1)) { Af[i, i + 1] <- 1; Af[i + 1, i] <- 1 }
Qf  <- diag(rowSums(Af)) - Af
## The checkout-installed INLA package ships no precompiled external libs,
## so point fbesag at its OWN installed shlib (R CMD INSTALL compiled it from
## the same src/fbesag.c that is baked into the binary). The binary resolves
## the registered model name from its cgeneric table either way; the file
## only has to EXIST for inla.cgeneric.define's R-side check.
fbso <- system.file("libs", paste0("fbesag", .Platform$dynlib.ext), package = "fbesag")
stopifnot(nzchar(fbso))
mfb <- fbesag::get_fbesag(graph = Qf, id = rep(1:2, each = nf / 2),
                          sd_gamma = 0.15, param = list(p1 = 1, p2 = 1e-5),
                          useINLAprecomp = FALSE, libpath = fbso)
set.seed(3)
yf <- rnorm(nf, 0, 0.1)
check_both(function()
    inla(y ~ 1 + f(idx, model = mfb),
         data = list(y = yf, idx = 1:nf), family = "gaussian"),
    "fbesag")

## INLAspacetime model 102 (sstspde, also compiled in): a small space-time
## field on a coarse mesh -- the heaviest precision structure in this suite.
cat("== cgeneric: spacetime (model 102) ==\n")
library(INLAspacetime)
library(fmesher)
smesh <- fm_mesh_2d(cbind(c(0, 1, 0, 1, 0.5), c(0, 0, 1, 1, 0.5)),
                    max.edge = 0.6, offset = 0.3)
tmesh <- fm_mesh_1d(1:4)
## useINLAprecomp = FALSE: the checkout-installed INLA ships no precompiled
## external libs, so use the CRAN package's own compiled shlib (same source
## family); the binary resolves model 102 from its cgeneric table regardless.
stm <- stModel.define(smesh, tmesh, model = "102",
                      control.priors = list(prs    = c(0.5, 0.5),
                                            prt    = c(2, 0.5),
                                            psigma = c(1, 0.5)),
                      useINLAprecomp = FALSE)
set.seed(4)
nst <- 60
loc <- cbind(runif(nst), runif(nst))
tim <- sample(1:4, nst, replace = TRUE)
Ast <- inla.spde.make.A(smesh, loc = loc, group = tim, group.mesh = tmesh)
yst <- rnorm(nst, 0, 0.3)
stk <- inla.stack(data = list(y = yst), A = list(Ast, 1),
                  effects = list(field = 1:(smesh$n * tmesh$n),
                                 intercept = rep(1, nst)))
check_both(function()
    inla(y ~ -1 + intercept + f(field, model = stm),
         data = inla.stack.data(stk),
         control.predictor = list(A = inla.stack.A(stk)),
         family = "gaussian"),
    "spacetime-102")
cat("cgeneric OK\n")

outdir <- argv[2]
if (!is.na(outdir) && nzchar(outdir)) {
    unlink(outdir, recursive = TRUE)
    r2 <- inla(y ~ x + f(idx, model = "iid"),
               data = data.frame(y = y, x = x, idx = idx),
               family = "gaussian",
               keep = TRUE, working.directory = outdir)
    ## the files may sit in a subdirectory of the working directory
    ini <- list.files(outdir, pattern = "^Model\\.ini$",
                      recursive = TRUE, full.names = TRUE)
    if (length(ini) == 0) {
        cat("contents of", outdir, ":\n")
        print(list.files(outdir, recursive = TRUE))
        stop("no Model.ini found under ", outdir)
    }
    ## make the export relocatable: the ini references its data files by
    ## absolute path, which only exists on this machine
    dir  <- dirname(normalizePath(ini[1]))
    txt  <- readLines(ini[1])
    txt  <- gsub(paste0(dir, "/"), "./", txt, fixed = TRUE)
    writeLines(txt, ini[1])
    cat("test model exported:", ini[1], "\n")
}
EOF
