#!/usr/bin/env bash
## Prove the freshly built inla binary computes, not just links: install the
## R package from this checkout, point it at the binary, and run a small
## model with a known answer. Fails on any R error, a non-finite marginal
## likelihood, or parameter estimates away from the truth.
##
## Knobs: PREFIX (default: <repo>/local) -- must match ci/build.sh.
set -e -o pipefail

ROOT=$(cd "$(dirname "$0")/.." && pwd)
PREFIX=${PREFIX:-$ROOT/local}
INLA_BIN=$PREFIX/bin/inla

## 1. The binary answers at all. (libR.so lives outside the default loader
##    path; harmless when the binary was built without libR.)
export LD_LIBRARY_PATH="/usr/lib/R/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
"$INLA_BIN" -ping

## 2. Package dependencies into a private, user-writable library
##    (cached by the workflow so the install runs once). On Ubuntu, prefer
##    Posit's mirror: it serves prebuilt Linux binaries of CRAN packages,
##    so nothing needs compiling; plain CRAN is the fallback.
export R_LIBS_USER=$PREFIX/Rlib
mkdir -p "$R_LIBS_USER"
. /etc/os-release 2>/dev/null || true
if [ "${ID:-}" = "ubuntu" ] && [ -n "${VERSION_CODENAME:-}" ]; then
    export SMOKE_CRAN_REPOS="https://packagemanager.posit.co/cran/__linux__/${VERSION_CODENAME}/latest https://cloud.r-project.org"
else
    export SMOKE_CRAN_REPOS="https://cloud.r-project.org"
fi
Rscript --vanilla -e '
    lib   <- Sys.getenv("R_LIBS_USER")
    repos <- strsplit(Sys.getenv("SMOKE_CRAN_REPOS"), " ")[[1]]
    need  <- c("fmesher", "lifecycle", "rlang", "withr", "MatrixModels")
    miss  <- setdiff(need, rownames(installed.packages()))
    if (length(miss))
        install.packages(miss, lib = lib, repos = repos)
'

## 3. The package's NAMESPACE is generated, not tracked: create it the same
##    way upstream does (roxygen; see rinla/R/Makefile) when it is missing.
##    The testthat_print definition mirrors that Makefile's document() call.
if [ ! -f "$ROOT/rinla/NAMESPACE" ]; then
    ## Roxygen's loader performs a minimal install, which itself requires
    ## some NAMESPACE file -- seed a placeholder that roxygen immediately
    ## replaces with the generated one. (Upstream never hits this: a
    ## previously generated NAMESPACE is always present in their tree.)
    ## The signature line matters: roxygen only overwrites a NAMESPACE that
    ## declares itself roxygen-generated.
    echo '# Generated by roxygen2: do not edit by hand' > "$ROOT/rinla/NAMESPACE"
    if ! Rscript --vanilla -e '
        lib   <- Sys.getenv("R_LIBS_USER")
        repos <- strsplit(Sys.getenv("SMOKE_CRAN_REPOS"), " ")[[1]]
        if (!requireNamespace("roxygen2", quietly = TRUE))
            install.packages("roxygen2", lib = lib, repos = repos)
        assign("testthat_print", function(...) print(...), envir = globalenv())
        roxygen2::roxygenize(commandArgs(TRUE)[1])
    ' "$ROOT/rinla"; then
        rm -f "$ROOT/rinla/NAMESPACE"      # do not leave the placeholder behind
        exit 1
    fi
    grep -q "^export" "$ROOT/rinla/NAMESPACE" \
        || { echo "ERROR: NAMESPACE was not regenerated"; rm -f "$ROOT/rinla/NAMESPACE"; exit 1; }
fi

## 4. The R package from this checkout (R side only; it ships no binaries,
##    the binary comes from ci/build.sh via the inla.call option below).
R CMD INSTALL --library="$R_LIBS_USER" --no-docs --no-help --no-byte-compile \
    "$ROOT/rinla"

## 5. A small Gaussian model with a known answer.
Rscript --vanilla - "$INLA_BIN" <<'EOF'
argv <- commandArgs(trailingOnly = TRUE)
library(INLA)
inla.setOption(inla.call = argv[1])
inla.setOption(num.threads = "2:1")

set.seed(1)
n   <- 300
x   <- rnorm(n)
idx <- 1:n
y   <- 1 + 0.7 * x + rnorm(n, sd = 0.3) + rnorm(n, sd = 0.2)

r <- inla(y ~ x + f(idx, model = "iid"),
          data   = data.frame(y = y, x = x, idx = idx),
          family = "gaussian")

stopifnot(is.finite(r$mlik[1]))
b <- r$summary.fixed
stopifnot(abs(b["(Intercept)", "mean"] - 1.0) < 0.1)
stopifnot(abs(b["x", "mean"] - 0.7) < 0.1)
cat("smoke test OK: mlik =", r$mlik[1], "\n")
EOF
