download :; git clone git@github.com:esmail-abdulfattah/gmrfs
build :;  make -C gmrfs/src -f ../../../Makefile.generic CC="$(CC)" CXX="$(CXX)" FC="$(FC)" FLAGS="$(FLAGS)" INC="$(INC)"
clean :; rm -rf gmrfs
.PHONY: download build clean

