#!/usr/bin/env bash
set -vx

win=0
for arg in "$@"; do
    case "$arg" in 
	*mingw*gcc*) win=1;;
    esac
done
if [ $win = 0 ]; then
    FLAGS="$FLAGS -rdynamic"
fi

echo $win
exit 1

DD=""
for p in *; do
    if [ -d "$p" -a -f "$p/Makefile" ]; then
	echo -e "\n\tProcess package [$p]\n"
	DD="$p $DD"
	(
	    cd $p
	    make download "$@"
	    find . -name cgeneric.h | while read f; do  mv -vf "$f" "$f"-disabled; done
	    make build FLAGS="$FLAGS" "$@"
	)
    fi
done

./update-cgeneric

for D in $DD; do 
    (
	cd $D
	L=lib$D.a
	find . -name \*.o | while read f; do ar crvs $L "$f"; done
	mv -v -f $L ..
    )
done
