#!/usr/bin/env bash
set -vx

for p in *; do
    if [ -d "$p" ]; then
	echo -e "\n\tProcess package [$p]\n"
	(
	    cd $p
	    make clean
	    make download
	    find . -name cgeneric.h | while read f; do  mv -vf "$f" "$f"-disabled; done
	    make build "$@"
	)
    fi
done

./update-cgeneric
