#!/usr/bin/env bash
h="cgeneric-table.h"
hh="cgeneric-defs.h"
H="cloglike-table.h"
HH="cloglike-defs.h"

for f in "$h" "$hh" "$H" "$HH"; do
    test -f "$f" && rm -rf "$f";
done

## CGENERIC
{
    for f in $(find . -name FUNCTIONS); do
	if [ -f "$f" ]; then 
	    echo Process $f >&2 
	    cat "$f" | awk '{for (i = 1;i <=NF; i++) print $i}' | \
		sort | uniq | tr -d ';' | \
		awk '/^[ \t]*#/ {next}
    	    { print "{ \"" $1 "\", (inla_cgeneric_func_tp *)" $1 " }," }'
	fi
    done
} | sort | uniq > $h

{
    for f in $(find . -name FUNCTIONS); do
	if [ -f "$f" ]; then 
	    echo Process $f >&2 
	    cat "$f" | awk '{for (i = 1;i <=NF; i++) print $i}' | \
		sort | uniq | tr -d ';' | \
		awk '/^[ \t]*#/ {next}
    	    { print "inla_cgeneric_func_tp " $1 ";" }'
	fi
    done
} | sort | uniq > $hh

## CLOGLIKE
{
    for f in $(find . -name CLOGLIKE); do
	if [ -f "$f" ]; then 
	    echo Process $f >&2 
	    cat "$f" | awk '{for (i = 1;i <=NF; i++) print $i}' | \
		sort | uniq | tr -d ';' | \
		awk '/^[ \t]*#/ {next}
    	    { print "{ \"" $1 "\", (inla_cloglike_func_tp *)" $1 " }," }'
	fi
    done
} | sort | uniq > $H

{
    for f in $(find . -name CLOGLIKE); do
	if [ -f "$f" ]; then 
	    echo Process $f >&2 
	    cat "$f" | awk '{for (i = 1;i <=NF; i++) print $i}' | \
		sort | uniq | tr -d ';' | \
		awk '/^[ \t]*#/ {next}
    	    { print "inla_cloglike_func_tp " $1 ";" }'
	fi
    done
} | sort | uniq > $HH
