#!/usr/bin/env bash

if [ $# -eq 0 ]; then
    echo 'Usage: $0 INLA_TAG [USER@IP]'
    exit 0
fi

umask 0022
tt=$(mktemp)
if [ $# -eq 2 ]; then
    IP=$2
else
    grep -v 192.168.122.158 ~/.ssh/known_hosts  > $tt && mv -f $tt ~/.ssh/known_hosts
    IP=0.0.0.0
    for ip in $(~/bin/my-vm-addr); do
	if ping -q -i1 -W1 -c1 $ip; then
	    IP=$ip
	    echo Host $IP is alive
	    break
	else
	    echo Host $ip is not alive
	fi
    done

    if [ -n "$IP" ]; then
	yes yes | ssh -x hrue@$IP echo Testing connection
    else 
	echo "No VM, exit"
	exit 1
    fi
fi

export INLA_TAG="${1-devel}"
VERSION=$(ssh -x $IP "if [ -f /etc/os-release ]; then source /etc/os-release; echo \$NAME-\$VERSION \$(uname -m); else echo Mac-\$(sw_vers --productVersion)--\$(uname -m); fi");
D=64bit
case "$VERSION" in
    Mac*x86*) OS=mac;;
    Mac*arm64) OS=mac.arm64; D="";;
    *) OS=linux;;
esac

## add so we can define 'devel' to compile the most recent one
if [ $INLA_TAG != "devel" ]; then
    ssh -x -t $IP "
    . .bash_profile;
    export INLA_TAG=$INLA_TAG;
    B=\$(echo builds/*);
    if \[ \! -d \$B \]; then B=builds/aarch64; fi;
    echo \$B;
    make -C \$B download;"
else
    ssh -x -t $IP "
    . .bash_profile;
    B=\$(echo builds/*);
    if \[ \! -d \$B \]; then B=builds/aarch64; fi;
    echo \$B;
    cd \$B/r-inla; 
    git reset --hard; 
    git checkout devel; 
    git pull --all"
fi
    

ssh -x -t $IP "
    . .bash_profile;
    set -x ;
    export INLA_TAG=$INLA_TAG;
    B=\$(echo builds/*);
    echo \$B;
    make -j2 -C\$B update;
    test -d \$B/64bit && rm -rf \$B/64bit;
    mkdir \$B/64bit;
    rsync -auv \$B/r-inla/rinla/inst/bin/$OS/$D/. \$B/64bit/.;
    cp -v \$B/local/bin/fmesher \$B/64bit/.;
    rsync -auv \$B/external-packages/external \$B/$D;
    if [ -f /etc/os-release ]; then
        ldd=bin/my.ldd
    else	   
        ldd=bin/my.otool
   fi	
    \$ldd \$B/local/bin/fmesher | while read f; do cp -v \$f \$B/64bit; done
    if test -f \$B/local/bin/inla; then 
        cp -v \$B/local/bin/inla \$B/64bit;
        \$ldd \$B/local/bin/inla | while read f; do cp -v \$f \$B/64bit; done;
    fi	
    if test -f \$B/local/bin/inla.mkl; then 
        cp -v \$B/local/bin/inla.mkl \$B/64bit;
        \$ldd \$B/local/bin/inla.mkl | while read f; do cp -v \$f \$B/64bit; done;
    fi	
"

B=$(ssh -x $IP 'echo builds/*')

tarfile="64bit.tgz"
ssh -x $IP 'cd '$B'/64bit; mv -f -v libRblas* first; mv -f -v libblas* first; mv -f -v liblapack* first; mv -f -v libopenblas* first'
ssh -x $IP 'cd '$B'/64bit; mv -f -v lib*malloc* malloc'
ssh -x $IP 'cd '$B'/64bit; mv -f -v libstdc* first; mv -f -v libgcc* first; mv -f -v libpardiso* first'
ssh -x $IP 'cd '$B'/64bit; rm -f -v libc.so*; rm -f -v libpthread.so*; rm -f -v librt.so*; rm -f -v libm.so*; rm -rf -v libdl.so*; rm -rf -v libflexiblas.so*'
ssh -x $IP "cd '$B'; tar cvfz $tarfile 64bit"
DD=$(ssh -x $IP 'if [ -f /etc/os-release ]; then echo "www/Linux-builds"; else echo "www/Mac-builds"; fi')
d="$DD/$VERSION/$INLA_TAG"
mkdir -p "$d"
rsync $IP:$B/$tarfile "$d"

(
    cd $DD
    f="FILES"
    test -f "$f" && rm "$f"
    find . -type f -print | grep -v md5sum.txt | sort > $f
)

