#!/usr/bin/env bash

is_set() {
    [[ -n "${1}" ]] && [[ ${!1+x} ]]
}


export INLA_MAC=${INLA_MAC-"rueh@kw-16659.kaust.edu.sa"}
export INLA_MAC_ARM64=${INLA_MAC_ARM64-"rueh@kw-18302.kaust.edu.sa"}

IP=0.0.0.0
for ip in $(~/bin/my-vm-addr); do
    if ping -q -i1 -W1 -c1 $ip; then
	IP=$ip
	echo Host $IP is alive
	break
    else
	echo Host $ip is not alive
    fi
done


if [ -n "$IP" ]; then
    export INLA_LINUX=hrue@$IP
    export INLA_LINUX_PORT=22
    yes yes | ssh -x hrue@$IP echo Testing connection
fi

output () {
    echo "$0: $@"
}

if [ $# -eq 0 ]; then
    echo $0: TAG
    exit 1
fi

if [ ! -d r-inla ]; then
    echo "No directory [r-inla]"
    exit 1
fi
git -C r-inla push --all --prune

export INLA_TAG="$1"
if git -C r-inla push origin $INLA_TAG; then
    echo push tag $INLA_TAG: OK
else
    echo push tag INLA_TAG: FAILED
    exit 1
fi

tt=$(mktemp)
grep -v 192.168.122.158 ~/.ssh/known_hosts  > $tt && mv -f $tt ~/.ssh/known_hosts
	
export INLA_VERSION=$(echo $INLA_TAG | awk -F_ '{print $2}')
output INLA_MAC=$INLA_MAC
output INLA_MAC_ARM64=$INLA_MAC_ARM64
output INLA_LINUX=$INLA_LINUX
output INLA_WINDOWS=$INLA_WINDOWS
output INLA_TAG=$INLA_TAG
output INLA_VERSION=$INLA_VERSION

shift 1
exec make -f Makefile "$@"
