#!/usr/bin/env bash
d="INLA/inst/bin"

fix-perm () {
    local d
    local f
    for d in "$@"; do
	for f in {fmesher,inla}{,.run,.exe}; do
	    test -f "$d/$f" && chmod 755 "$d/$f"
	done
	for lib in "$d"/*.a "$d"/*.so "$d"/*.so.* "$d"/*.dylib "$d"/*.dll; do
	    test -f "$lib" && chmod 644 "$lib"
	done
	      
    done
}

## Maybe put them somewhere else, but for the moment, its here
rsync -auv ~/p/inla/pardiso $d
fix-perm $d/pardiso

for m in 64; do
    DIR=$d/mac/${m}bit
    for p in inla inla.mkl fmesher; do 
	for f in $(ssh $INLA_MAC bin/my.otool builds/build$m/local/bin/$p) builds/build$m/local/bin/$p; do
	    echo sync $f
	    rsync -auvL $INLA_MAC:$f $DIR/.
	done
    done
    fix-perm $DIR
    ## those we like be be first
    mv -f -v $DIR/libjemalloc.* $DIR/first
done

for m in 64; do
    DIR=$d/linux/${m}bit
    for p in inla inla.mkl fmesher; do 
	for f in $(ssh -p $INLA_LINUX_PORT $INLA_LINUX bin/my.ldd builds/build$m/local/bin/$p) builds/build$m/local/bin/$p; do
	    echo sync $f
	    rsync --rsh="ssh -p $INLA_LINUX_PORT" -auvL $INLA_LINUX:$f $DIR/.
	done
    done
    fix-perm $DIR
    ## these ones, we do not want or need
    rm -f $DIR/libc.so*
    rm -f $DIR/libpthread.so*
    rm -f $DIR/librt.so*
    rm -f $DIR/libm.so*
    ## those we like be be first
    mv -f -v $DIR/libjemalloc.* $DIR/first
done

for m in 32 64; do
    DIR=$d/windows/${m}bit
    for p in inla fmesher; do 
	for f in $(ssh -p $INLA_LINUX_PORT $INLA_LINUX builds/windows$m/bin/my.objdump builds/windows$m/local/bin/$p.exe) builds/windows$m/local/bin/$p.exe; do
	    echo sync $f
	    rsync --rsh="ssh -p $INLA_LINUX_PORT" -auvL $INLA_LINUX:$f $DIR/.
	done
    done
    fix-perm $DIR
done

